addons:
    apt:
        packages:
            - g++-4.8
            - libasound2-dev
        sources:
            - ubuntu-toolchain-r-test
    chrome: stable
before_install: npm install npm@latest --global
cache:
    directories:
        - $HOME/.npm
dist: xenial
env:
    global:
        - secure: ynxFxP3HiPP1IXCn8zmMu+1PhbUVSc4YIkBxC36U0qoMdHZ7GHuQ/9QiWqNy4aFj9sEKnONjO7NLY9tDwMPOoXhBCwHb0WB2bNIUX9nF+qcT+I0Qb317I2d8PYHQah6Fyridi4p7TOrrKjriZuwwvDQInhYo+VHaKMJsewOET4O4aY97cg9N6cNQokuBM4lj2EoKf9BYW//Jr2famF4q5sX2shCD6HgInmufcwVWK9y5r4rb4788t2DOrwxRbKnp0DQRXFX9G0Y1mVXS05I37jcvubW68KPNz9YiA1Ziemu3b6iC38nIy1kllWmOnYgrwn5PeOs9E8vwoWQjhj2+OhawOEBu4mhx1h/R90z1SefdlbOOaLhFTJYC0wp3YYozhoa3hbFVIqHZMrWbCY8XVVHZAmEa80CdfEvuUnD+BKraJrSx4ds1zX0q20nNx7WHDFggX+Jc65YoUeYcXKZte12tvIC/da/M5ScEDJB76PWt/85xlXWEtR32m7cc+/mQk5/5GFFE78cPDRTLgWFDfL+8kYTCoWJQkVzFPjR7e0m2384etZaidPJLDH/SH05Cq1LQpN4jXsa753yZWyP1upjp1P8MnEBbu44KlIWYIw6fHLf0FxTJ+KH+WuGhlMAt8ZD1DBDUCzAmpA6Eq3bvBRWkLNDVilys0Y02bQSG7dk=
        - secure: wqW84hmEpqxAgImgHEj2ylBGAaFzj5up/FEiEO873+Gvi0q7wYS4Ll36zTEn88ERsNmpAa5gP9tMKtkqwo14DhXdgIP8G5jra2vJFcDcx9qjQcr+B1eYJh5VlZDnlE+Yb2stn9K+8gYHMsmavoo9AAWY65kmHdoya7PXfldG7CE+PMqbwc3hEA2+kkMy/P8vrhvJ284IX1nsSWKDlJ4ymsxQWWGInFICMGzcuqo/VNADZoLI2VR9XeYQKvPe3pKRtZxfOcgVP7nayN23iA8JWXUcc/psgIY8757Ryfwgq7bqsU0ORVdqhcGQIgkd7iyi9brgcGl+vhRNVRPnbheHvy63/oajCmF71cX7cwy0gr/1OfEEdc1SXpwbS/+c5Zof80V9L/pgQGUsM0QbD+7YRICP2FZxp4Hiw9fHUkf5HDxjdNWhKJf+kWYQ5gHKRjKj2bi1/8yxbCY2OrwMwvXaIolbwA0cxpr17wCrL3KGG7ZZFSsamX5QY9+sNw+wRrjBULBhdEnPYBEIwuqH0vIl2QwdYFQ7/lnMXNBqv/UNLHC8785XoiYXWG96r77eVnu0YKWrR5S7FZngQFafG89BpMTvosgJZa+ZXQylAIUtG/0getBHeijDD2s7+md0+la1yrGAR4pjsm1lgP2iQDQBSFJo731yAI6dD2wKCpS3ntU=
install: npm ci || (rm -rf node_modules && npm install)
language: node_js
matrix:
    include:
        - env: [TARGET=chrome, TYPE=integration]
          node_js: 12
        - env: [TARGET=chrome, TYPE=unit]
          node_js: 12
        - env: [TARGET=firefox, TYPE=integration]
          node_js: 12
        - env: [TARGET=firefox, TYPE=unit]
          node_js: 12
script: sudo env "PATH=$PATH" npm test
